name:  PostMessager
author:  davidwalsh
current:  0.2
category:  Request
tags:  [window,postMessage,crossdomain,ajax]
docs:  http://davidwalsh.name/js/postmessager
demo:  http://davidwalsh.name/js/postmessager
